# Generated by Django 3.0.1 on 2020-06-02 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0092_auto_20200602_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomdobr', models.CharField(help_text='Номер обращения', max_length=20, verbose_name='Номер')),
                ('text', models.TextField(help_text='Комментарий', null=True, verbose_name='Текст')),
                ('datecre', models.DateField(auto_now_add=True, help_text='Дата создания', null=True, verbose_name='Дата создания')),
                ('datebzm', models.DateField(auto_now=True, help_text='Дата изменения', null=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('2', 'Заблокировано'), ('1', 'На блокировке'), ('3', 'Отказано'), ('0', 'На блокировку')], default='0', help_text='Статус блокировки', max_length=50, verbose_name='Статус')),
                ('user', models.ForeignKey(help_text='Кто направил на блокировку', null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.Person')),
            ],
            options={
                'verbose_name': 'ответ',
                'verbose_name_plural': 'ответы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(null=True, upload_to='photos', verbose_name='Фотография')),
                ('otv', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='block.Appeal', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
            },
        ),
    ]
