# Generated by Django 3.0.1 on 2020-06-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0093_auto_20200603_1602'),
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ['pk'], 'verbose_name': 'блокировка', 'verbose_name_plural': 'блокировки'},
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('3', 'Отказано'), ('1', 'На блокировке'), ('0', 'В работе'), ('2', 'Заблокировано')], default='0', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='text',
            field=models.TextField(blank=True, help_text='Комментарий', null=True, verbose_name='Текст'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('chstatus', models.CharField(choices=[('3', 'Отказано'), ('1', 'На блокировке'), ('2', 'Заблокировано')], default='1', help_text='Статус блокировки', max_length=50, verbose_name='Статус')),
                ('datecre', models.DateTimeField(auto_now_add=True, help_text='Дата создания', null=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(help_text='Кто направил на блокировку', null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.Person')),
            ],
        ),
    ]
