# Generated by Django 3.0.1 on 2020-06-03 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20200603_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='block.Appeal', verbose_name='Обращение на блокировку'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('1', 'На блокировке'), ('2', 'Заблокировано'), ('0', 'В работе'), ('3', 'Отказано')], default='0', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='result',
            name='chstatus',
            field=models.CharField(choices=[('1', 'На блокировке'), ('2', 'Заблокировано'), ('3', 'Отказано')], default='1', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
    ]
