# Generated by Django 3.0.1 on 2020-06-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_auto_20200611_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ['-datecre'], 'verbose_name': 'блокировка', 'verbose_name_plural': 'блокировки'},
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('0', 'В работе'), ('1', 'На блокировке'), ('3', 'Отклоненно'), ('2', 'Закрыто')], default='0', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='result',
            name='chstatus',
            field=models.CharField(choices=[('0', 'В работе'), ('1', 'На блокировке'), ('3', 'Отклоненно'), ('2', 'Закрыто')], default='1', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
    ]
