# Generated by Django 3.0.1 on 2020-07-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0007_auto_20200703_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('0', 'В работе'), ('4', 'На согласовании'), ('2', 'Закрыто'), ('1', 'На блокировке'), ('3', 'Отклонено')], default='4', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='result',
            name='chstatus',
            field=models.CharField(choices=[('0', 'В работе'), ('4', 'На согласовании'), ('2', 'Закрыто'), ('1', 'На блокировке'), ('3', 'Отклонено')], default='1', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
    ]
