# Generated by Django 3.0.1 on 2020-07-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0008_auto_20200706_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='datecre',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания', null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('4', 'На согласовании'), ('3', 'Отклонено'), ('2', 'Закрыто'), ('1', 'На блокировке'), ('0', 'В работе')], default='4', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='result',
            name='chstatus',
            field=models.CharField(choices=[('4', 'На согласовании'), ('3', 'Отклонено'), ('2', 'Закрыто'), ('1', 'На блокировке'), ('0', 'В работе')], default='1', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
    ]
