# Generated by Django 3.0.1 on 2020-07-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0101_auto_20200709_1035'),
        ('block', '0009_auto_20200708_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='datebzm',
            field=models.DateTimeField(auto_now=True, help_text='Дата изменения', null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('4', 'На согласовании'), ('1', 'На блокировке'), ('2', 'Закрыто'), ('3', 'Отклонено'), ('0', 'В работе')], default='4', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='result',
            name='chstatus',
            field=models.CharField(choices=[('4', 'На согласовании'), ('1', 'На блокировке'), ('2', 'Закрыто'), ('3', 'Отклонено'), ('0', 'В работе')], default='1', help_text='Статус блокировки', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(help_text='Кто направил на сообщение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.Person'),
        ),
    ]
