# Generated by Django 3.0.1 on 2020-04-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0082_auto_20200401_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecre', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='problem.Problem', verbose_name='Обращение')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.Person', verbose_name='Автор')),
            ],
        ),
    ]
