# Generated by Django 3.0.1 on 2020-04-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-datecre'], 'verbose_name': 'сообщение по обращению', 'verbose_name_plural': 'сообщения по обращениям'},
        ),
        migrations.AlterField(
            model_name='message',
            name='datecre',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
