# Generated by Django 3.0.1 on 2020-04-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200401_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['datecre'], 'verbose_name': 'сообщение по обращению', 'verbose_name_plural': 'сообщения по обращениям'},
        ),
    ]
