# Generated by Django 3.0.1 on 2020-01-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Куратор проблемы', max_length=40, verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'куратор проблемы',
                'verbose_name_plural': 'кураторы проблем',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Minis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ЦИОГВ', max_length=40, verbose_name='ЦИОГВ')),
            ],
            options={
                'verbose_name': 'ЦИОГВ',
                'verbose_name_plural': 'ЦИОГВ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomdobr', models.CharField(help_text='Номер проблемы', max_length=20, verbose_name='Номер')),
                ('temat', models.CharField(blank=True, help_text='Тематика проблемы', max_length=20, null=True, verbose_name='Тематика')),
                ('text', models.TextField(blank=True, help_text='Текст проблемы', null=True, verbose_name='Текст')),
                ('adres', models.CharField(blank=True, help_text='Адрес проблемы', max_length=255, null=True, verbose_name='Адрес')),
                ('url', models.URLField(blank=True, help_text='URL проблемы', null=True, verbose_name='URL')),
                ('datecre', models.DateField(blank=True, help_text='Дата создания', null=True, verbose_name='Дата создания')),
                ('datecrok', models.DateField(blank=True, help_text='Срок задачи', null=True, verbose_name='Срок задачи')),
                ('dateotv', models.DateField(blank=True, help_text='Дата ответа исполнителя', null=True, verbose_name='Дата ответа исполнителя')),
                ('status', models.CharField(blank=True, help_text='Статус проблемы', max_length=50, null=True, verbose_name='Статус')),
                ('ciogv', models.ForeignKey(blank=True, help_text='ЦИОГВ', null=True, on_delete=django.db.models.deletion.PROTECT, to='problem.Minis', verbose_name='ЦИОГВ')),
                ('curat', models.ForeignKey(blank=True, help_text='Куратор', null=True, on_delete=django.db.models.deletion.PROTECT, to='problem.Curator', verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'жалоба',
                'verbose_name_plural': 'жалобы',
                'ordering': ['nomdobr'],
            },
        ),
    ]
