# Generated by Django 3.0.1 on 2020-01-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20200113_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='curat',
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Срок', null=True, verbose_name='Срок')),
                ('desck', models.TextField(blank=True, help_text='Текст проблемы', null=True, verbose_name='Текст')),
                ('curat', models.ForeignKey(blank=True, help_text='Куратор', null=True, on_delete=django.db.models.deletion.PROTECT, to='problem.Curator', verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'срок жалобы',
                'verbose_name_plural': 'сроки жалоб',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='datecrok',
            field=models.OneToOneField(blank=True, help_text='Срок задачи', null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Term', verbose_name='Срок задачи'),
        ),
    ]
