# Generated by Django 3.0.1 on 2020-01-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20200114_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='parsing',
            field=models.CharField(default='Noparsing', help_text='Статус парсинга', max_length=50, verbose_name='Статус парсинга'),
        ),
        migrations.AlterField(
            model_name='term',
            name='curat',
            field=models.ForeignKey(help_text='Куратор', on_delete=django.db.models.deletion.PROTECT, to='problem.Curator', verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='term',
            name='desck',
            field=models.TextField(blank=True, help_text='Описание', null=True, verbose_name='Описание'),
        ),
    ]
