# Generated by Django 3.0.1 on 2020-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='nomdobr',
            field=models.CharField(help_text='Номер проблемы', max_length=20, unique=True, verbose_name='Номер'),
        ),
    ]
