# Generated by Django 3.0.1 on 2020-01-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20200116_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='lvl',
            field=models.CharField(choices=[('r', 'Чтение'), ('w', 'Запись')], default=1, help_text='Организация', max_length=40, verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
