# Generated by Django 3.0.1 on 2020-01-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_access_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('1', 'На согласовании'), ('0', 'На исполнении'), ('2', 'Исполнено')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='access',
            name='dost',
            field=models.ManyToManyField(to='problem.Curator', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='access',
            name='lvl',
            field=models.CharField(choices=[('w', 'Запись'), ('r', 'Чтение')], help_text='Уровень доступа', max_length=40, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='temat',
            field=models.CharField(blank=True, help_text='Тематика проблемы', max_length=255, null=True, verbose_name='Тематика'),
        ),
    ]
