# Generated by Django 3.0.1 on 2020-02-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_auto_20200204_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='datecrok',
            field=models.ManyToManyField(blank=True, help_text='Сроки задачи', null=True, related_name='terms', to='problem.Term', verbose_name='Сроки задачи'),
        ),
        migrations.AlterField(
            model_name='term',
            name='otv',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otvs', to='problem.Answer'),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('0', 'На исполнении'), ('1', 'На согласовании'), ('2', 'Исполнено')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
    ]
