# Generated by Django 3.0.1 on 2020-02-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_auto_20200204_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='datecrok',
        ),
        migrations.AddField(
            model_name='problem',
            name='datecrok',
            field=models.ManyToManyField(blank=True, help_text='Сроки задачи', null=True, related_name='terms', to='problem.Term', verbose_name='Сроки задачи'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='parsing',
            field=models.CharField(choices=[('1', 'Обновлено'), ('0', 'На обновлении')], default='0', help_text='Статус парсинга', max_length=50, verbose_name='Статус парсинга'),
        ),
        migrations.AlterField(
            model_name='term',
            name='otv',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otvs', to='problem.Answer'),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('1', 'На согласовании'), ('0', 'На исполнении'), ('2', 'Исполнено')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
    ]
