# Generated by Django 3.0.1 on 2020-02-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0018_auto_20200205_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='post',
            field=models.CharField(default=None, help_text='Должность', max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('1', 'Утверждено'), ('0', 'На согласовании')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='dateotv',
            field=models.DateField(blank=True, help_text='Дата ответа по доброделу', null=True, verbose_name='Дата ответа по доброделу'),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('1', 'На согласовании'), ('0', 'На исполнении'), ('2', 'Исполнено')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
    ]
