# Generated by Django 3.0.1 on 2020-02-17 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0022_auto_20200217_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='podcat',
            field=models.ForeignKey(blank=True, help_text='Подкатегория проблемы', null=True, on_delete=django.db.models.deletion.PROTECT, to='problem.Podcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('1', 'Утверждено'), ('0', 'На согласовании')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='parsing',
            field=models.CharField(choices=[('0', 'На обновлении'), ('1', 'Обновлено')], default='0', help_text='Статус парсинга', max_length=50, verbose_name='Статус парсинга'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='temat',
            field=models.ForeignKey(blank=True, help_text='Тематика проблемы', null=True, on_delete=django.db.models.deletion.PROTECT, to='problem.Category', verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('2', 'Исполнено'), ('1', 'На согласовании'), ('0', 'На исполнении')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
    ]
