# Generated by Django 3.0.1 on 2020-02-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0025_auto_20200217_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='datecrok',
        ),
        migrations.RemoveField(
            model_name='term',
            name='otv',
        ),
        migrations.AddField(
            model_name='answer',
            name='term',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Term'),
        ),
        migrations.AddField(
            model_name='term',
            name='problem',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('0', 'На исполнении'), ('1', 'На согласовании'), ('2', 'Исполнено')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
    ]
