# Generated by Django 3.0.1 on 2020-02-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0029_auto_20200217_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='anwr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statussys',
            field=models.CharField(choices=[('0', 'Закрыто'), ('1', 'В работе'), ('2', 'На модерации')], default='2', help_text='Статус проблемы', max_length=70, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('1', 'На согласовании'), ('2', 'Исполнено'), ('0', 'На исполнении')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post',
            field=models.CharField(blank=True, default=' ', help_text='Должность', max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
