# Generated by Django 3.0.1 on 2020-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0033_auto_20200218_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('0', 'На согласовании'), ('2', 'Ответ отклонен'), ('1', 'Утверждено')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statussys',
            field=models.CharField(choices=[('1', 'В работе'), ('0', 'Закрыто'), ('2', 'На модерации')], default='2', help_text='Статус проблемы', max_length=70, verbose_name='Статус'),
        ),
    ]
