# Generated by Django 3.0.1 on 2020-02-25 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0045_auto_20200225_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resolution',
            new_name='Termhistory',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='resolutions',
        ),
        migrations.AddField(
            model_name='term',
            name='curatuser',
            field=models.ForeignKey(help_text='Куратор пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curatuser', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AddField(
            model_name='term',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('2', 'Ответ отклонен'), ('1', 'Утверждено'), ('0', 'На согласовании')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='parsing',
            field=models.CharField(choices=[('1', 'Обновлено'), ('0', 'На обновлении')], default='0', help_text='Статус парсинга', max_length=50, verbose_name='Статус парсинга'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statussys',
            field=models.CharField(choices=[('2', 'На модерации'), ('1', 'В работе'), ('0', 'Закрыто')], default='2', help_text='Статус проблемы', max_length=70, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='visible',
            field=models.CharField(choices=[('0', 'Не показывать'), ('1', 'Показывать')], default='1', help_text='Режим показа на сайте', max_length=50, verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='term',
            name='curat',
            field=models.ForeignKey(help_text='Куратор', null=True, on_delete=django.db.models.deletion.PROTECT, to='problem.Curator', verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('2', 'Исполнено'), ('0', 'На исполнении'), ('1', 'На согласовании')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
    ]
