# Generated by Django 3.0.1 on 2020-02-25 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0046_auto_20200225_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['date'], 'verbose_name': 'назначение', 'verbose_name_plural': 'назначения'},
        ),
        migrations.AlterModelOptions(
            name='termhistory',
            options={'ordering': ['user'], 'verbose_name': 'резолюция', 'verbose_name_plural': 'резолюции'},
        ),
        migrations.RemoveField(
            model_name='termhistory',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='termhistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='termhistory',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='termhistory',
            name='prob',
        ),
        migrations.AddField(
            model_name='term',
            name='datecre',
            field=models.DateField(auto_now_add=True, help_text='Дата создания', null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='termhistory',
            name='term',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='problem.Term'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('1', 'Утверждено'), ('0', 'На согласовании'), ('2', 'Ответ отклонен')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statussys',
            field=models.CharField(choices=[('2', 'На модерации'), ('0', 'Закрыто'), ('1', 'В работе')], default='2', help_text='Статус проблемы', max_length=70, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='term',
            name='curat',
            field=models.ForeignKey(blank=True, help_text='Куратор', null=True, on_delete=django.db.models.deletion.PROTECT, to='problem.Curator', verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='term',
            name='curatuser',
            field=models.ForeignKey(blank=True, help_text='Куратор пользователь', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curatuser', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('1', 'На согласовании'), ('0', 'На исполнении'), ('2', 'Исполнено')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
    ]
