# Generated by Django 3.0.1 on 2020-06-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0096_auto_20200611_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(default=None, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'ход решения',
                'verbose_name_plural': 'ходы решения',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='access',
            name='lvl',
            field=models.CharField(choices=[('r', 'Чтение'), ('w', 'Запись')], help_text='Уровень доступа', max_length=40, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('2', 'Ответ отклонен'), ('1', 'Утверждено'), ('0', 'На согласовании')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statussys',
            field=models.CharField(choices=[('0', 'Закрыто'), ('1', 'В работе'), ('2', 'На модерации')], default='2', help_text='Статус проблемы', max_length=70, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='term',
            name='status',
            field=models.CharField(choices=[('0', 'На исполнении'), ('2', 'Исполнено'), ('1', 'На согласовании')], default='0', help_text='Статус ответа', max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, verbose_name='URL изображения')),
                ('decis', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.DecisionProblem', verbose_name='Ход решения')),
                ('prob', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem', verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='EditProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecre', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('prob', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editprob', to='problem.Problem', verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'изменение обращения',
                'verbose_name_plural': 'изменения обращений',
                'ordering': ['-datecre'],
            },
        ),
        migrations.CreateModel(
            name='Editable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, null=True, verbose_name='Название')),
                ('lastval', models.TextField(default=None, null=True, verbose_name='Старое значение')),
                ('newval', models.TextField(default=None, null=True, verbose_name='Новое значение')),
                ('operation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editable', to='problem.EditProblem', verbose_name='Операция изменения')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='decisionproblem',
            name='prob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem', verbose_name='Обращение'),
        ),
    ]
