# Generated by Django 3.0.1 on 2020-02-21 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название парсера', max_length=40, verbose_name='Парсер')),
                ('datecre', models.DateField(auto_now_add=True, help_text='Дата создания', null=True, verbose_name='Дата создания')),
                ('status', models.CharField(help_text='Статус проблемы', max_length=70, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'парсер',
                'verbose_name_plural': 'парсеры',
                'ordering': ['datecre'],
            },
        ),
    ]
