# Generated by Django 3.0.1 on 2020-02-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'парсер',
                'verbose_name_plural': 'парсеры',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='parser',
            name='status',
            field=models.ForeignKey(help_text='Статус проблемы', on_delete=django.db.models.deletion.PROTECT, to='parsers.Status', verbose_name='Статус'),
        ),
    ]
