# Generated by Django 3.0.1 on 2020-02-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_auto_20200221_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name': 'статус паресер', 'verbose_name_plural': 'статусы парсеров'},
        ),
    ]
