# Generated by Django 3.0.1 on 2020-03-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_auto_20200221_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название действия')),
                ('nact', models.CharField(max_length=40, verbose_name='Номер действия')),
            ],
            options={
                'verbose_name': 'действие',
                'verbose_name_plural': 'действия',
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveField(
            model_name='parser',
            name='uuid',
        ),
        migrations.AddField(
            model_name='parser',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parser',
            name='session',
            field=models.CharField(default=None, max_length=40, null=True, verbose_name='Номер сессии'),
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'На выполнении'), ('1', 'Выполнено')], default='0', max_length=50, verbose_name='Статус')),
                ('lastaction', models.DateTimeField(auto_now=True, null=True, verbose_name='Время выполнения')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='parsers.Action', verbose_name='Действие')),
                ('pars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parsers', to='parsers.Parser', verbose_name='Парсер')),
            ],
            options={
                'verbose_name': 'история действия',
                'verbose_name_plural': 'истории действий',
                'ordering': ['pk'],
            },
        ),
    ]
