# Generated by Django 3.0.1 on 2020-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_auto_20200302_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionhistory',
            name='arg',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Аргументы'),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнено'), ('0', 'На выполнении')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
