# Generated by Django 3.0.1 on 2020-03-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_auto_20200302_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='pars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parsers', to='parsers.Parser', verbose_name='Парсер'),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('0', 'На выполнении'), ('1', 'Выполнено')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
