# Generated by Django 3.0.1 on 2020-03-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_auto_20200303_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loggings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Обновлено'), ('0', 'Добавлено')], default='0', max_length=50, verbose_name='Статус')),
                ('note', models.CharField(blank=True, default=None, max_length=100, verbose_name='Примечание')),
                ('datecre', models.DateField(auto_now_add=True, help_text='Дата создания', null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='actionhistory',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнено'), ('0', 'На выполнении')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
