# Generated by Django 3.0.1 on 2020-03-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0008_auto_20200304_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнено'), ('0', 'На выполнении')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loggings',
            name='name',
            field=models.CharField(choices=[('0', 'Добавлено'), ('2', 'Прочее'), ('1', 'Обновлено')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
