# Generated by Django 3.0.1 on 2020-03-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0014_auto_20200310_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('0', 'На выполнении'), ('2', 'Ошибка'), ('1', 'Выполнено')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loggings',
            name='name',
            field=models.CharField(choices=[('2', 'Прочее'), ('0', 'Добавлено'), ('1', 'Обновлено')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default=None, verbose_name='Ошибка')),
                ('datecre', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('act', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parsers.ActionHistory', verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
                'ordering': ['pk'],
            },
        ),
    ]
