# Generated by Django 3.0.1 on 2020-03-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0018_auto_20200316_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('0', 'На выполнении'), ('2', 'Ошибка'), ('1', 'Выполнено')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loggings',
            name='name',
            field=models.CharField(choices=[('1', 'Обновлено'), ('2', 'Прочее'), ('0', 'Добавлено')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
