# Generated by Django 3.0.1 on 2020-03-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0021_auto_20200317_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('0', 'На выполнении'), ('2', 'Ошибка'), ('1', 'Выполнено')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loggings',
            name='name',
            field=models.CharField(choices=[('0', 'Добавлено'), ('1', 'Обновлено'), ('2', 'Прочее')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
