# Generated by Django 3.0.1 on 2020-04-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0029_auto_20200401_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('0', 'На выполнении'), ('2', 'Ошибка'), ('1', 'Выполнено')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
