# Generated by Django 3.0.1 on 2020-04-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0031_auto_20200401_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('0', 'На выполнении'), ('1', 'Выполнено'), ('2', 'Ошибка')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loggings',
            name='name',
            field=models.CharField(choices=[('1', 'Обновлено'), ('0', 'Добавлено'), ('2', 'Прочее')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
