# Generated by Django 3.0.1 on 2020-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0033_auto_20200403_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнено'), ('0', 'На выполнении'), ('2', 'Ошибка')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loggings',
            name='name',
            field=models.CharField(choices=[('0', 'Добавлено'), ('2', 'Прочее'), ('1', 'Обновлено')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
