# Generated by Django 3.0.1 on 2020-06-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0036_auto_20200601_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнено'), ('2', 'Ошибка'), ('0', 'На выполнении')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
