# Generated by Django 3.0.1 on 2020-06-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0038_auto_20200602_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('0', 'На выполнении'), ('1', 'Выполнено'), ('2', 'Ошибка')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
