# Generated by Django 3.0.1 on 2020-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0039_auto_20200602_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('2', 'Ошибка'), ('0', 'На выполнении'), ('1', 'Выполнено')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loggings',
            name='name',
            field=models.CharField(choices=[('2', 'Прочее'), ('0', 'Добавлено'), ('1', 'Обновлено')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
