# Generated by Django 3.0.1 on 2020-06-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0041_auto_20200603_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('2', 'Ошибка'), ('1', 'Выполнено'), ('0', 'На выполнении')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loggings',
            name='name',
            field=models.CharField(choices=[('1', 'Обновлено'), ('0', 'Добавлено'), ('2', 'Прочее')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
