# Generated by Django 3.0.1 on 2020-06-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0044_auto_20200611_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionhistory',
            options={'ordering': ['lastaction'], 'verbose_name': 'история действия', 'verbose_name_plural': 'истории действий'},
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнено'), ('2', 'Ошибка'), ('0', 'На выполнении')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loggings',
            name='name',
            field=models.CharField(choices=[('0', 'Добавлено'), ('2', 'Прочее'), ('1', 'Обновлено')], default='0', max_length=50, verbose_name='Статус'),
        ),
    ]
