# Generated by Django 3.0.1 on 2020-07-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0099_auto_20200706_1634'),
        ('parsers', '0046_auto_20200703_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logpars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecre', models.DateTimeField(auto_now_add=True, help_text='Дата создания', null=True, verbose_name='Дата создания')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logpars', to='problem.Problem', verbose_name='Проблема')),
            ],
            options={
                'verbose_name': 'история парсера',
                'verbose_name_plural': 'истории парсера',
                'ordering': ['datecre'],
            },
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('2', 'Ошибка'), ('1', 'Выполнено'), ('0', 'На выполнении')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Logspars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', 'Изменение тематики'), ('3', 'Обновление даты ответа'), ('1', 'Изменение подкатегории'), ('4', 'Обновление статуса'), ('2', 'Добавление автора')], default='0', max_length=255, null=True, verbose_name='Название операции')),
                ('lastval', models.CharField(default=None, max_length=255, null=True, verbose_name='Предыдущее значение')),
                ('newval', models.CharField(default=None, max_length=255, null=True, verbose_name='Новое значение')),
                ('oper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logspars', to='parsers.Logpars', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'история парсера',
                'verbose_name_plural': 'истории парсера',
                'ordering': ['pk'],
            },
        ),
    ]
