# Generated by Django 3.0.1 on 2020-07-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0047_auto_20200706_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logpars',
            options={'ordering': ['-datecre'], 'verbose_name': 'история парсера', 'verbose_name_plural': 'истории парсера'},
        ),
        migrations.AlterField(
            model_name='actionhistory',
            name='status',
            field=models.CharField(choices=[('1', 'Выполнено'), ('2', 'Ошибка'), ('0', 'На выполнении')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='loggings',
            name='name',
            field=models.CharField(choices=[('1', 'Обновлено'), ('2', 'Прочее'), ('0', 'Добавлено')], default='0', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='logspars',
            name='name',
            field=models.CharField(choices=[('4', 'Обновление статуса'), ('1', 'Изменение подкатегории'), ('0', 'Изменение тематики'), ('2', 'Добавление автора'), ('3', 'Обновление даты ответа')], default='0', max_length=255, null=True, verbose_name='Название операции'),
        ),
    ]
